### PR TITLE
[nit] swap generator_darwin_{no,}cgo.go

### PR DESCRIPTION
**Pull request by astj**
File names and build constraints are mismatching. I swapped those 2 files so that their filename properly show build constraints.

### CODE REVIEW

**Comment by astj** [comment]
I don't know why macOS 10.8+cgo fails..

**Comment by astj** [comment]
macOS + 10.8 + cgo fails even in master, so this p-r is not bad, I hope.

**Comment by astj** [comment]
(rebased master containing #3)

**Comment by itchyny** [comment]
LGTM

**Comment by astj** [comment]
Thanks!

**Pull request merged**
