### PR TITLE
Read more values from /proc/meminfo on Linux.

### PR DESCRIPTION
**Pull request by heptalium**

### CODE REVIEW

**Comment by pyto86pri** [comment]
Hi @heptalium , Thank you for your contribution.
It seems good to add extra fields, but I'm not sure if the way `memory.User` calculated is reasonable or not.
I think memory usage of use space can be calculated as sum of `memory.Active` and `memory.Inactive`.
How do you think?

**Comment by heptalium** [comment]
Hi, for the calculation of the user space memory I used the formula that the Munin Monitoring memory plugin is using (https://github.com/munin-monitoring/munin/blob/master/plugins/node.d.linux/memory, the parameter is called apps there). They define the memory of user space applications as everything that is not free, cache, buffer and the other kernel structures. Active and inactive seems to include also kernel space memory.
Maybe there is a better name for this parameter or it can be omitted because it can be calculated of the other values.

**Comment by pyto86pri** [comment]
I see. Thank you for your explanation.
Although Munin does calculate the memory usage of user space in that way, I couldn't confirm it's a common/reasonable way.
So, I'm sorry, but could you please omit the `memory.User` as you suggested?

**Comment by heptalium** [comment]
OK, I removed the calculation again.

**Review by pyto86pri — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
